### ISSUE TITLE
File chooser does not navigate to correct directory on Windows

### ISSUE THREAD

**Issue by Marukyu** [Marukyu/NecroEdit#7]
When first selecting the "Open" or "Save" action in the editor, the file chooser displays the user's home directory, rather than navigating to the "Dungeons" subdirectory within the game folder, as is the case on Linux.

This appears to be a defect within TinyFileDialogs. More testing is required.

**Comment by vareille** [comment]
this is corrected on tinyfiledialogs version 2.8

**Comment by Marukyu** [comment]
Thank you very much for the fix, @chafporte!
